function GEOMertsincostancot = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  GEOMERTSINCOSTANCOT = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GEOMERTSINCOSTANCOT = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  GEOMertsincostancot = importfile1("C:\Users\Bondz\Desktop\Papier Vampiere\GEOMert sin cos tan cot.cs", [1, 1]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Apr-2019 21:37:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "sinxcos2xcosXcos2x";
opts.VariableTypes = "string";
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
GEOMertsincostancot = readtable(filename, opts);

end