%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Bondz\Desktop\Bonifaciloga.qasm
%
% Auto-generated by MATLAB on 16-Apr-2019 05:14:22

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "nx";
opts.VariableTypes = "string";
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Bonifaciloga = readtable("C:\Users\Bondz\Desktop\Bonifaciloga.qasm", opts);


%% Clear temporary variables
clear opts